### PR TITLE
Issue 7 : WIP for JMAP authentication

### PR DESCRIPTION
**Pull request by rouazana**
WIP for JMAP authentication, reworked after first review comments

### CODE REVIEW

**Comment by mbaechler** [comment]
:+1:

**Comment by chibenwa** [comment]
+1

**Comment by aduprat** [comment]
:+1:

**Comment by chibenwa** [comment]
Euh I have a more general remark : 

We are mixing requests / responses handling with servlet / http specific stuff in the protocol module.
What is done elsewhere in James is to have interaction of well defined request / responses with the rest of James in the protocol module, and have the connectivity technology ( eg netty, javax.servlet ) defined in James server.

I think this is something they are attached to ( cf Eric CHarles mail => in the architecture he mentions it is written in big ).

We also have advantages to do that : changing of http echnology ( eg servlets to spark )  would be trivial.

What do you think about this ? ( and sorry for realising this that late... )

**Comment by aduprat** [comment]
Could be implemented later, as the interactions are very tiny actually.

**Comment by rouazana** [comment]
Merged in a new JMAP branch.

**Pull request closed without merging**
